//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transformer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bushing_db
    {
        public int PK_Bushing_Id { get; set; }
        public string Designation { get; set; }
        public string Winding { get; set; }
        public string Serial_Number { get; set; }
        public string Manufacturer { get; set; }
        public string Type { get; set; }
        public string Rated_KV { get; set; }
        public string Power_Factor_C1 { get; set; }
        public string Power_Factor_C2 { get; set; }
        public string Capacitance_C1 { get; set; }
        public string Capacitance_C2 { get; set; }
        public Nullable<int> FK_Test_Id { get; set; }
        public string Date { get; set; }
        public Nullable<int> FK_User_Id { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
    }
}
