//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transformer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bushing_C
    {
        public int PK_C_Id { get; set; }
        public string Type { get; set; }
        public Nullable<int> FK_Test_Id { get; set; }
        public Nullable<int> FK_User_Id { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
        public string Bushing { get; set; }
        public string Serial_Number { get; set; }
        public string B_PF { get; set; }
        public string B_Capacitance { get; set; }
        public string Test_KV { get; set; }
        public string Corr_Factor { get; set; }
        public string Test_Mode { get; set; }
        public string mA { get; set; }
        public string Watts { get; set; }
        public string pF { get; set; }
        public string pF_Corr { get; set; }
        public string Capacitance { get; set; }
    }
}
