//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transformer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circuit_db
    {
        public int PK_Circuit_Id { get; set; }
        public string i1 { get; set; }
        public string i2 { get; set; }
        public string i3 { get; set; }
        public string i4 { get; set; }
        public string i5 { get; set; }
        public string i6 { get; set; }
        public string i7 { get; set; }
        public string i8 { get; set; }
        public string i9 { get; set; }
        public string i10 { get; set; }
        public string i11 { get; set; }
        public string j1 { get; set; }
        public string j2 { get; set; }
        public string j3 { get; set; }
        public string j4 { get; set; }
        public string j5 { get; set; }
        public string j6 { get; set; }
        public string j7 { get; set; }
        public string j8 { get; set; }
        public string j9 { get; set; }
        public string j10 { get; set; }
        public string j11 { get; set; }
        public string k1 { get; set; }
        public string k2 { get; set; }
        public string k3 { get; set; }
        public string k4 { get; set; }
        public string k5 { get; set; }
        public string k6 { get; set; }
        public string k7 { get; set; }
        public string k8 { get; set; }
        public string k9 { get; set; }
        public string k10 { get; set; }
        public string k11 { get; set; }
        public Nullable<int> FK_Test_Id { get; set; }
        public Nullable<int> FK_User_Id { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
    }
}
