//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transformer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insulation_db
    {
        public int PK_Insulation_Id { get; set; }
        public string i1 { get; set; }
        public string i2 { get; set; }
        public string i3 { get; set; }
        public string i4 { get; set; }
        public string i5 { get; set; }
        public string i6 { get; set; }
        public string i7 { get; set; }
        public string i8 { get; set; }
        public string i9 { get; set; }
        public string i10 { get; set; }
        public string i11 { get; set; }
        public string i12 { get; set; }
        public string i13 { get; set; }
        public string i14 { get; set; }
        public string i15 { get; set; }
        public string i16 { get; set; }
        public string i17 { get; set; }
        public string i18 { get; set; }
        public string i19 { get; set; }
        public string i20 { get; set; }
        public string i21 { get; set; }
        public string i22 { get; set; }
        public string i23 { get; set; }
        public string i24 { get; set; }
        public string i25 { get; set; }
        public string i26 { get; set; }
        public string i27 { get; set; }
        public string i28 { get; set; }
        public string i29 { get; set; }
        public string i30 { get; set; }
        public string j1 { get; set; }
        public string j2 { get; set; }
        public string j3 { get; set; }
        public string j4 { get; set; }
        public string j5 { get; set; }
        public string j6 { get; set; }
        public string j7 { get; set; }
        public string j8 { get; set; }
        public string j9 { get; set; }
        public string j10 { get; set; }
        public string j11 { get; set; }
        public string j12 { get; set; }
        public string j13 { get; set; }
        public string j14 { get; set; }
        public string j15 { get; set; }
        public string j16 { get; set; }
        public string j17 { get; set; }
        public string j18 { get; set; }
        public string j19 { get; set; }
        public string j20 { get; set; }
        public string j21 { get; set; }
        public string j22 { get; set; }
        public string j23 { get; set; }
        public string j24 { get; set; }
        public string j25 { get; set; }
        public string j26 { get; set; }
        public string j27 { get; set; }
        public string j28 { get; set; }
        public string j29 { get; set; }
        public string j30 { get; set; }
        public Nullable<int> FK_Test_Id { get; set; }
        public Nullable<int> FK_User_Id { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
    }
}
