//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transformer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransformerEntities : DbContext
    {
        public TransformerEntities()
            : base("name=TransformerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bushing_C> Bushing_C { get; set; }
        public virtual DbSet<Bushing_db> Bushing_db { get; set; }
        public virtual DbSet<Circuit_db> Circuit_db { get; set; }
        public virtual DbSet<Insulation_db> Insulation_db { get; set; }
        public virtual DbSet<Overall_db> Overall_db { get; set; }
        public virtual DbSet<Tap_Charger_db> Tap_Charger_db { get; set; }
        public virtual DbSet<Test_db> Test_db { get; set; }
        public virtual DbSet<Transformer_db> Transformer_db { get; set; }
        public virtual DbSet<Turns_Ratio_Data> Turns_Ratio_Data { get; set; }
        public virtual DbSet<Turns_Ratio_Select> Turns_Ratio_Select { get; set; }
        public virtual DbSet<User_db> User_db { get; set; }
        public virtual DbSet<Winding_Data> Winding_Data { get; set; }
        public virtual DbSet<Winding_Select> Winding_Select { get; set; }
    }
}
