//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transformer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Overall_db
    {
        public int PK_O_Id { get; set; }
        public Nullable<int> FK_Test_Id { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
        public string Test_KV_1 { get; set; }
        public string Test_KV_2 { get; set; }
        public string Test_KV_3 { get; set; }
        public string Test_KV_4 { get; set; }
        public string Test_KV_5 { get; set; }
        public string Test_KV_6 { get; set; }
        public string Co_Factor_1 { get; set; }
        public string Co_Factor_2 { get; set; }
        public string Co_Factor_3 { get; set; }
        public string Co_Factor_4 { get; set; }
        public string Co_Factor_5 { get; set; }
        public string Co_Factor_6 { get; set; }
        public string Co_Factor_7 { get; set; }
        public string Co_Factor_8 { get; set; }
        public string Co_Factor_9 { get; set; }
        public string Co_Factor_10 { get; set; }
        public string mA_1 { get; set; }
        public string mA_2 { get; set; }
        public string mA_3 { get; set; }
        public string mA_4 { get; set; }
        public string mA_5 { get; set; }
        public string mA_6 { get; set; }
        public string mA_7 { get; set; }
        public string mA_8 { get; set; }
        public string mA_9 { get; set; }
        public string mA_10 { get; set; }
        public string Watts_1 { get; set; }
        public string Watts_2 { get; set; }
        public string Watts_3 { get; set; }
        public string Watts_4 { get; set; }
        public string Watts_5 { get; set; }
        public string Watts_6 { get; set; }
        public string Watts_7 { get; set; }
        public string Watts_8 { get; set; }
        public string Watts_9 { get; set; }
        public string Watts_10 { get; set; }
        public string pF_1 { get; set; }
        public string pF_2 { get; set; }
        public string pF_3 { get; set; }
        public string pF_4 { get; set; }
        public string pF_5 { get; set; }
        public string pF_6 { get; set; }
        public string pF_7 { get; set; }
        public string pF_8 { get; set; }
        public string pF_9 { get; set; }
        public string pF_10 { get; set; }
        public string pF_Co_1 { get; set; }
        public string pF_Co_2 { get; set; }
        public string pF_Co_3 { get; set; }
        public string pF_Co_4 { get; set; }
        public string pF_Co_5 { get; set; }
        public string pF_Co_6 { get; set; }
        public string pF_Co_7 { get; set; }
        public string pF_Co_8 { get; set; }
        public string pF_Co_9 { get; set; }
        public string pF_Co_10 { get; set; }
        public string Cap_1 { get; set; }
        public string Cap_2 { get; set; }
        public string Cap_3 { get; set; }
        public string Cap_4 { get; set; }
        public string Cap_5 { get; set; }
        public string Cap_6 { get; set; }
        public string Cap_7 { get; set; }
        public string Cap_8 { get; set; }
        public string Cap_9 { get; set; }
        public string Cap_10 { get; set; }
        public Nullable<int> FK_User_Id { get; set; }
    }
}
