//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transformer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tap_Charger_db
    {
        public int PK_Tap_Id { get; set; }
        public string Description { get; set; }
        public string Naming_Preference { get; set; }
        public string Manufacturer { get; set; }
        public string Type { get; set; }
        public string Steps { get; set; }
        public string Increase { get; set; }
        public string Decrease { get; set; }
        public string Oil_Volume { get; set; }
        public string Name_Plate { get; set; }
        public string Date { get; set; }
        public Nullable<int> FK_Test_Id { get; set; }
        public Nullable<int> FK_User_Id { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
        public string TC { get; set; }
    }
}
