//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transformer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_db
    {
        public int PK_Test_Id { get; set; }
        public string Test_Date { get; set; }
        public string Test_Time { get; set; }
        public string Air_Temperature { get; set; }
        public string Temperature_OTI { get; set; }
        public string Tester_Name { get; set; }
        public string Test_Set_Type { get; set; }
        public string Test_Set_Name { get; set; }
        public string Test_Set_Serial_Number { get; set; }
        public string Reason_For_Testing { get; set; }
        public string Travel_Time { get; set; }
        public string Crew_Size { get; set; }
        public string Duration_Of_Testing { get; set; }
        public Nullable<int> FK_Test_Id { get; set; }
        public Nullable<int> FK_User_Id { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
    }
}
