//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transformer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transformer_db
    {
        public int PK_Test_Id { get; set; }
        public string Type { get; set; }
        public string Facility_Name { get; set; }
        public string Plant_Number { get; set; }
        public string Substation { get; set; }
        public string Tag_no { get; set; }
        public string SAP_Equipment_Number { get; set; }
        public string Manufacturer_Name { get; set; }
        public string Serial_Number { get; set; }
        public string Mfg_Country { get; set; }
        public string Mfg_Year { get; set; }
        public string Transformer_Type { get; set; }
        public string Voltage_Rating_HV { get; set; }
        public string Voltage_Rating_LV { get; set; }
        public string Voltage_Rating_LV1 { get; set; }
        public string Voltage_Rating_LV2 { get; set; }
        public string Voltage_Rating_TV { get; set; }
        public string Rated_Power { get; set; }
        public string Rated_Power_Unit { get; set; }
        public string Phases { get; set; }
        public string Vector_Group { get; set; }
        public string Sealing_System { get; set; }
        public string Cooling_Type { get; set; }
        public string Oil_Type { get; set; }
        public string Oil_Weight { get; set; }
        public string Tapcharger_Type { get; set; }
        public string Oil_Temperature { get; set; }
        public string Oil_Temperature_Unit { get; set; }
        public string Humidity { get; set; }
        public string Ambient { get; set; }
        public string Ambient_Unit { get; set; }
        public Nullable<int> FK_User_Id { get; set; }
        public string Date { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
    }
}
