//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transformer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Winding_Select
    {
        public int PK_Winding_Id { get; set; }
        public string i1 { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
        public Nullable<int> FK_Test_Id { get; set; }
        public Nullable<int> FK_User_Id { get; set; }
    }
}
