//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transformer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Winding_Data
    {
        public int PK_Winding_Data_Id { get; set; }
        public string i1 { get; set; }
        public string i2 { get; set; }
        public string i3 { get; set; }
        public string i4 { get; set; }
        public string i5 { get; set; }
        public string i6 { get; set; }
        public string i7 { get; set; }
        public string i8 { get; set; }
        public string i9 { get; set; }
        public string i10 { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
        public Nullable<int> FK_Test_Id { get; set; }
        public Nullable<int> FK_User_Id { get; set; }
    }
}
